version: '3.8'

services:
  db:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: python:3.9
    container_name: python_app
    working_dir: /app
    volumes:
      - ./app:/app
    depends_on:
      - db
    command: ["python", "app.py"]

volumes:
  db_data:
