@startuml Pert5

left to right direction

actor User as "User"

rectangle "Source Code Pert4" {
    usecase "Input Angka" as input
    usecase "Call Void Tambah" as tambah
    usecase "Call Void Kurang" as kurang
    usecase "Call Void Kali" as kali
    usecase "Call Void Bagi" as bagi
    usecase "Input Angka2" as input2
    usecase "Output" as output
    usecase "Exit" as exit
}

User --> input
input --> menu : choice Menu
menu --> tambah 
tambah --> exit

User --> input
input --> menu : choice Menu
menu --> kurang
kurang --> exit

User --> input
input --> menu : choice Menu
menu --> kali
kali --> exit

User --> input
input --> menu : choice Menu
menu --> bagi
bagi --> exit

@enduml